### ISSUE TITLE
genome does not have chrom_name_path

### ISSUE THREAD

**Issue by houruiyan** [chung-lab/SCAFE#11]
Hello,  thank you for developing this awesome tool. I meet trouble when I use it. 
When I use the scafe.workflow.sc.solo, it always tell me that genome does not have chrom_name_path.
My code is looking like this.
`scafe.workflow.sc.solo --run_bam_path ./S17765-F11_S33_out/outs/possorted_genome_bam.bam --run_cellbarcode_path ./S17765-F11_S34_out/outs/filtered_feature_bc_matrix --genome /storage/yhhuang/users/ruiyan/software/SCAFE/resources/genome/my_hg38_encode   --run_tag S17765-F11_S33 --run_outDir ./S33_SCAFE_out`

However, I got the error.
![image](https://user-images.githubusercontent.com/56068158/141644757-62e8e681-8c9c-4074-bb60-012c3d682ff9.png)

Hope to get your help. I found that some people have the same questions. But he solved it by re-downloading the  reference genome. However, I did it according to his analysis. I found that it is not helpful to me. On the one hand, I download the resources.genome. `./scafe.download.resources.genome --genome hg38.gencode_v32 ` On the other hand, I run the scafe.tool.cm.prep_genome. All of them do not work for me. 

Thank you in advance.

**Comment by jenchien** [comment]
The `--genome` parameter take the genome name installed in the `SCAFE/resources/genome/` folder, not the path. In your code, `--genome my_hg38_encode` should work. We may modify it in the future to make it more general. Thanks.

**Comment by houruiyan** [comment]
Thank  you very much!
