### ISSUE TITLE
The error when running the scafe.workflow.sc.pool 

### ISSUE THREAD

**Issue by houruiyan** [chung-lab/SCAFE#12]
Hello, I meet another trouble. Hope you can help me. Thank you in advance.
I want to combine three samples into one pool. Firstly, I create my own lib_list_path.txt. It looks like this.

S17765-F11_S33  1       /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S33_SCAFE_out/bam_to_ctss/S17765-F11_S33/bed/S17765-F11_S33.UMI_CB.ctss.bed.gz    /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S17765-F11_S33_out/outs/filtered_feature_bc_matrix/barcodes.tsv.gz        /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S33_SCAFE_out/bam_to_ctss/S17765-F11_S33/bed/S17765-F11_S33.CB.ctss.bed.gz
S17765-F11_S34  2       /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S34_SCAFE_out/bam_to_ctss/S17765-F11_S34/bed/S17765-F11_S34.UMI_CB.ctss.bed.gz    /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S17765-F11_S34_out/outs/filtered_feature_bc_matrix/barcodes.tsv.gz        /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S34_SCAFE_out/bam_to_ctss/S17765-F11_S34/bed/S17765-F11_S34.CB.ctss.bed.gz
S17765-F11_S36  3       /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S36_SCAFE_out/bam_to_ctss/S17765-F11_S36/bed/S17765-F11_S36.UMI_CB.ctss.bed.gz    /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S36_SCAFE_out/bam_to_ctss/S17765-F11_S36/bed/S17765-F11_S36.CB.ctss.bed.gz        /storage/yhhuang/users/ruiyan/MS_Cambridge/S17765-F11/S17765-F11_S36_out/outs/filtered_feature_bc_matrix/barcodes.tsv.gz

Then I run the script as this 
`scafe.workflow.sc.pool --overwrite=yes --lib_list_path=./lib_list_path.txt --genome=hg38.gencode_v32 --run_tag=S17765-F11 --run_outDir=./sc.pool`

However, it produces an error like this
![image](https://user-images.githubusercontent.com/56068158/141790374-25375ea9-6899-4c76-907f-b9e56fb13e83.png)

But I have the count file folder in every sample. 
![image](https://user-images.githubusercontent.com/56068158/141790595-493d3b6c-fe85-4958-b3ef-4c480c1ab702.png)
I do not what is the origin of question. Hope to get your help. Thank you!

**Comment by chung-lab** [comment]
the last row of your lib_list_path.txt (S17765-F11_S36) has switched cellbarcode and CB_ctss_bed column.
the script took your CB_ctss_bed as your cellbarcode lists and found "chr1" as a cellbarcode and complained "chr1" is duplicated.
