### ISSUE TITLE
Results of count not found. Quitting

### ISSUE THREAD

**Issue by houruiyan** [chung-lab/SCAFE#13]
Hello  Dr. Chung, I am really really sorry. But I cannot fix it. I still run the scafe.workflow.sc.pool
My lib is like this:
`S17765-F11_S33  33      ./S33_SCAFE_out/bam_to_ctss/S17765-F11_S33/bed/S17765-F11_S33.UMI_CB.ctss.bed.gz        ./S17765-F11_S33_out/outs/filtered_feature_bc_matrix/S17765-F11_S33.barcodes.tsv.gz     ./S33_SCAFE_out/bam_to_ctss/S17765-F11_S33/bed/S17765-F11_S33.CB.ctss.bed.gz
S17765-F11_S34  34      ./S34_SCAFE_out/bam_to_ctss/S17765-F11_S34/bed/S17765-F11_S34.UMI_CB.ctss.bed.gz        ./S17765-F11_S34_out/outs/filtered_feature_bc_matrix/S17765-F11_S34.barcodes.tsv.gz     ./S34_SCAFE_out/bam_to_ctss/S17765-F11_S34/bed/S17765-F11_S34.CB.ctss.bed.gz
S17765-F11_S35  35      ./S35_SCAFE_out/bam_to_ctss/S17765-F11_S35/bed/S17765-F11_S35.UMI_CB.ctss.bed.gz        ./S17765-F11_S35_out/outs/filtered_feature_bc_matrix/S17765-F11_S35.barcodes.tsv.gz     ./S35_SCAFE_out/bam_to_ctss/S17765-F11_S35/bed/S17765-F11_S35.CB.ctss.bed.gz
S17765-F11_S36  36      ./S36_SCAFE_out/bam_to_ctss/S17765-F11_S36/bed/S17765-F11_S36.UMI_CB.ctss.bed.gz        ./S17765-F11_S36_out/outs/filtered_feature_bc_matrix/S17765-F11_S36.barcodes.tsv.gz     ./S36_SCAFE_out/bam_to_ctss/S17765-F11_S36/bed/S17765-F11_S36.CB.ctss.bed.gz`

My code is 
`nohup scafe.workflow.sc.pool --overwrite=yes --lib_list_path=./lib_list_path.txt --genome=hg38.gencode_v32 --run_tag=demo --run_outDir=./sc.pool &`

However it gives me this error.
![image](https://user-images.githubusercontent.com/56068158/141954498-63fb7c12-61c8-4b14-85d5-4216c7a2b4ae.png)

This time, I already check the lib_list_path clearly. However, it still throw this error. Hope to get your help. Thank you!

**Comment by chung-lab** [comment]
try to use full path in ./lib_list_path.txt
