### ISSUE TITLE
About "mouse ENCODE CREs"

### ISSUE THREAD

**Issue by jiawei-zhong** [chung-lab/SCAFE#16]
Hi,

I would like to generate reference using "scafe.tool.cm.prep_genome". Could you please tell me where to download mouse ENCODE CREs.

Many thanks in advance!

Jiawei

**Comment by jenchien** [comment]
If you're working with mouse data, we do have a pre-built genome that can be downloaded by `download.resources.genome --genome mm10.gencode_vM25`

**Comment by jiawei-zhong** [comment]
Thanks for answering me and I have already downloaded that. But I want to use another gencode annotation (like vM29, the latest version). So could you please tell me where to download mouse ENCODE CREs?

**Comment by jenchien** [comment]
For the genome we provided, the CRE region used in `--mask_bed_path` was downloaded from **[SCREEN: Search Candidate cis-Regulatory Elements by ENCODE](https://screen.encodeproject.org/)** . The direct link to all mouse cCRE is [HERE](https://api.wenglab.org/screen_v13/fdownloads/V3/mm10-cCREs.bed)

**Comment by jiawei-zhong** [comment]
That is exactly what I want! Thanks!
