### ISSUE TITLE
dropbox access failed 

### ISSUE THREAD

**Issue by marsa04** [chung-lab/SCAFE#17]
Dear SCAFE team,

Check your dropbox files, please. 
It seems that the files that need to be downloaded through the _scafe.download.demo.input_ command are not available.

**Comment by jenchien** [comment]
Thanks for reporting the issue. I just tried it and was able to download the demo input. Would you mind to try it again, and post the error message if there is?

**Comment by marsa04** [comment]
This is an error that I've getting after run _scafe.download.demo.input_:

`Singularity> scafe.download.demo.input`
`--2022-06-28 08:09:27--  https://www.dropbox.com/s/iz3fqv6gy0ljrtp/input.tar.gz
Resolving www.dropbox.com (www.dropbox.com)... 162.125.66.18, 2620:100:6022:18::a27d:4212
Connecting to www.dropbox.com (www.dropbox.com)|162.125.66.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently`
`Location: /s/raw/iz3fqv6gy0ljrtp/input.tar.gz [following]`
`--2022-06-28 08:09:28--  https://www.dropbox.com/s/raw/iz3fqv6gy0ljrtp/input.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found`
`2022-06-28 08:09:28 ERROR 404: Not Found.`

**Comment by jenchien** [comment]
Hi, you might still be using the previous beta version. Could you update to the current release and try again? Thanks.
