### ISSUE TITLE
scafe not found when using singularity + docker image

### ISSUE THREAD

**Issue by ccrobertson** [chung-lab/SCAFE#19]
Hi there. Thanks for a great resource. We are excited to apply SCAFE to our data. 

I am trying to run SCAFE using the Docker image pulled from https://hub.docker.com/r/cchon/scafe using singularity: 
`singularity pull docker://cchon/scafe:latest`

However, when I try to use the docker image, SCAFE commands are not recognized. For example, running a shell:
`>singularity shell scafe_latest.sif`
`>scafe_latest.sif scafe.workflow.sc.solo --help`
returns this error:
`bash: scafe.workflow.sc.solo: command not found`

And executing the command:
`>singularity exec scafe_latest.sif scafe.workflow.sc.solo --help`
returns this error:
`/.singularity.d/actions/exec: 21: exec: scafe.workflow.sc.solo: not found`

Some googling suggests that this could happen if the image does not have `/bin/sh` in it (see https://github.com/apptainer/singularity/issues/2386)... in other words maybe it is a docker to singularity issue? Do you know if your docker container should be compatible in singularity?

Thanks for any help!

**Comment by chung-lab** [comment]
Thanks for using SCAFE.
We have not tested the Docker image with singularity and we received similar feedbacks on other users on this issue.
We're currently looking into this issue and will update the docker image to be singularit-compatible.
We'll let you know once updated and many thanks.

**Comment by chung-lab** [comment]
Try running this:

`singularity shell --writable --env APPEND_PATH=/SCAFE/scripts --env LC_ALL=C docker://cchon/scafe:latest`

the issue is related to PATH variable in  singularity containers. You have to add the scafe scripts (/SCAFE/scripts) to the path from the --env option. The other --env option LC_ALL=C is for suppressing some perl locale warnings.

**Comment by ccrobertson** [comment]
Thanks for your help with this! Apologies for the delayed follow up.

Appending `/SCAFE/scripts` to the PATH variable works for me, although it seems we must be using different version of singularity because `--env` was not a valid option in my version (singularity 3.5.1). But I was able to get the program to run using:

`SINGULARITYENV_APPEND_PATH=/SCAFE/scripts singularity exec scafe_latest.sif scafe.workflow.sc.solo --help`

or by appending it manually within the shell

`singularity shell scafe_latest.sif
PATH=/SCAFE/scripts:$PATH
`

The `--writable` option fails for me with the following error:

`FATAL:   no SIF writable overlay partition found in scafe_latest.sif`

Maybe this is also an issue with the singularity versions.
