### ISSUE TITLE
Illegal division by zero at scafe.tool.sc.bam_to_ctss

### ISSUE THREAD

**Issue by xibarrasoria** [chung-lab/SCAFE#21]
Hello,

I am facing a very similar error to #20:

> Illegal division by zero at ./SCAFE/scripts/scafe.tool.sc.bam_to_ctss line 1406.
> Died at ./SCAFE/scripts/scafe.workflow.sc.solo line 595.
 
I have checked I do have both R1 and R2 in my BAM file and the sequences are generally 95nt long. Demo tests ran successfully.

I have attached the first few lines of my BAM file. Any advice on what might be going wrong would be much appreciated.

Many thanks,
Ximena

[head.txt](https://github.com/chung-lab/SCAFE/files/9547304/head.txt)

**Comment by weitaiwu** [comment]
How do you solve this problem?

**Comment by weitaiwu** [comment]
I solved it!

**Comment by wunnies** [comment]
In my case, the cause of this problem was a missing .bai file. A .bam file by itself is insufficient to run bam_to_ctss
