### ISSUE TITLE
scafe.workflow.sc.solo dies at line 551

### ISSUE THREAD

**Issue by lanyanjun** [chung-lab/SCAFE#3]
Hi, I successfully installed SCAFE  and now I want to run scafe.workflow.sc.solo with my own data using the default options. However, I get following error message and was wondering why the script died? is it missing some files?

Thanks a lot in advance.

<img width="571" alt="Screen Shot 2021-04-05 at 12 49 52" src="https://user-images.githubusercontent.com/64237174/113535200-bcba4f80-960d-11eb-88dc-f7c64d266de6.png">

**Comment by chung-lab** [comment]
Seems the PROC R package was not properly installed. We would modify scafe for more robust checks for dependencies.
