### ISSUE TITLE
Bedtools issue

### ISSUE THREAD

**Issue by GBeattie** [chung-lab/SCAFE#4]
Hey,

I've installed all dependencies successfully, however SCAFE can't seem to find bedtools. Below is my attempt at running the demo data alongside proof that bedtools is both in the ./resources/bin folder and in my path (note: scafe.check.dependencies also can't find bedtools, I've also tried removing bedtools from my path in case there is a clash but same error occurs).

```
[regmgbe@login13 SCAFE]$ scafe.workflow.sc.solo --overwrite=yes --run_bam_path=./demo/input/sc.solo/demo.cellranger.bam --run_cellbarcode_path=./demo/input/sc.solo/demo.barcodes.tsv.gz --genome=hg19.gencode_v32lift37 --run_tag=demo --run_outDir=./demo/output/sc.solo/

#===========================#
Start running bam_to_ctss
#===========================#


=========================================================================
[2021-04-22 09:57] starts running ...... 
=========================================================================

[2021-04-22 09:57] Checking all SCAFE executables          
bedtools is not installed properly. Quitting.

#========================================#
Results of bam_to_ctss not found. Quitting.
#========================================#
Died at /home/regmgbe/Programmes/SCAFE/scripts/scafe.workflow.sc.solo line 551.
[regmgbe@login13 SCAFE]$ bedtools --version
bedtools v2.25.0
[regmgbe@login13 SCAFE]$ ls -l resources/bin/bedtools/
total 36516
-rwxrwxrwx 1 regmgbe regmx0 37387240 Apr 21 14:37 bedtools
```
Any help would be greatly appreciated!

**Comment by chung-lab** [comment]
scafe depends on the bedtools bin within its directory, and it will not use the system-wide bedtools bin.
It seems the resources/bin/bedtools/bedtools bin failed to execute.
you might replace the resources/bin/bedtools/bedtools with your system-wide bedtools bin 
and make sure  resources/bin/bedtools/bedtools  is executable.

**Comment by GBeattie** [comment]
I'm on a HPC cluster where bedtools is loaded as a module, so the easiest thing to do was to make sure the provided bedtools was executable (chmod 777), however the issue is still there.

```
[regmgbe@login13 SCAFE]$ ls -l resources/bin/bedtools/
total 36516
-rwxrwxrwx 1 regmgbe regmx0 37387240 Apr 21 14:37 bedtools
```

**Comment by GBeattie** [comment]
Think I've found the issue, looks to be a bedtools problem, feel free to close this if you think it's user specific.

```
[regmgbe@login13 bedtools]$ ./bedtools 
./bedtools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

```

**Comment by GBeattie** [comment]
Problem rectified by downloading + making bedtools from GitHub, followed by replacing the ./resources/bin/bedtools/bedtools executable with the executable from GitHub, test run completed successfully.

**Comment by chung-lab** [comment]
@GBeattie thanks for reporting. Appreciated. Would modify the script to use the system-wide executable as the second choice to avoid similar problem in future.
