### ISSUE TITLE
pooling of multiple samples

### ISSUE THREAD

**Issue by baigal628** [chung-lab/SCAFE#8]
Hi,

I am curious about how the scafe.workflow.sc.pool is functioning to merge all the tCREs across samples. As mentioned in README, I ran workflow.sc.solo on an individual sample first and used scafe.workflow.sc.pool to pool all the 64 samples together. In the single sample run, I got ~15,000 tCREs on average. But after pooling only ~9,800 was returned as in common. I am thinking if the merging criteria are too strict for my dataset.

I didn't find a description of how scafe.workflow.sc.pool is doing the pool step. It would be great if you can help to explain.

Thanks!

**Comment by jenchien** [comment]
Hi, as far as I know, `scafe.workflow.sc.pool` pools all samples at the ctss level, then calls and filters tssClusters by the same workflow as in `scafe.workflow.sc.solo`. Therefore, the unfiltered tssClusters for each sample will not necessarily appear in the pooled output. How many tCREs do you get after the pooled run? When you say "after pooling only ~9,800 was returned as in common", do you mean on average there are about 9800 pooled tCREs intersecting tCREs in each sample?
